### ISSUE TITLE
Library doesn't work in cljs over react-native

### ISSUE THREAD

**Issue by VyacheslavMik** [exoscale/lingo#12]
Hello! Thanks for your library.

I have an issue with this library in cljs that is used in a react-native project. When I require it I get an error: `find-ns-obj not supported for target react-native`, because of the following line 
https://github.com/exoscale/lingo/blob/6e5c360342153414c0b6c3019f9cc4e68466acd2/src/exoscale/lingo.cljc#L8

If I understand correctly this namespace is used only as a namespace for keywords. I think that a new mechanism in clojure will be more suitable. I mean `:as-alias` form in require - https://clojure.org/guides/learn/namespaces.

**Comment by mpenet** [comment]
The weird thing is that this line was added to remove a warning in cljs context only. We don't need an alias for it, so I don't think as-alias would change anything really. In theory, nothing prevents usage of non existing namespaces for keywords, yet cljs is quirky apparently when it comes to this. 

I'll check if removing this line makes any difference, if its removal just emits a warning I am fine with that.

**Comment by VyacheslavMik** [comment]
> Please try 1.0.4, hopefully it was fixed by #13

It works! Thank you very much!
